bookfair/urls.py
"""BookFair URL Configuration"""

# Django
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('fair.urls', 'fair'), namespace='fair')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fair/urls.py
"""Fair Urls"""

#Django
from django.urls import path

#Views
from fair import views

urlpatterns = [
    path(
        route='',
        view=views.IndexView.as_view(),
        name='index'
        ),
    path(
        route='noticia/<int:pk>',
        view=views.NoticeDetailView.as_view(),
        name='notice'
        ),
    path(
        route='pronto',
        view=views.SoonView.as_view(),
        name='soon'
        ),
]

content/models.py
from django.db import models

# Create your models here.

fair/models.py
"""Fair models"""

# Django
from django.db import models
from django.contrib.auth.models import User


class Image(models.Model):
    """Image Model"""
    footer = models.CharField(
        'Pie de foto',
        max_length=255,
    )
    photo = models.ImageField(
        'Foto',
        upload_to='section/notices')

    def __str__(self):
        """returrn title"""
        return self.footer


class Post(models.Model):
    """Post model """

    title = models.CharField('Título', max_length=500)
    photo = models.ManyToManyField(Image)
    lead = models.CharField('Lead Noticia', max_length=500)
    text = models.TextField('Texto Noticia')
    author = models.CharField('Autor', max_length=500)

    #metadata
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """return title"""
        return self.title

class Guest(models.Model):
    """Guest Model"""
    name = models.CharField('Nombre', max_length=500)
    title = models.CharField('Titulo', max_length=500)
    message = models.CharField('Mensaje', max_length=500)
    photo = models.ImageField(
        'Foto',
        upload_to='section/guests')
        
    def __str__(self):
        """returrn title"""
        return self.title

class Program(models.Model):
    """Programs model """

    title = models.CharField('Título', max_length=500)
    photo = models.ImageField(
        'Foto',
        upload_to='section/programs')
    text = models.TextField('Descripción Programa')

    #metadata
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """return title"""
        return self.title

class Topic(models.Model):
    """Topics models"""
    title = models.CharField('Título', max_length=500)
    number = models.CharField('Número', max_length=500)

    def __str__(self):
        """return topic and number"""
        return '{}: {}'.format(self.title,self.number)

content/views.py
from django.shortcuts import render

# Create your views here.

fair/views.py
"""Fair Views"""

# Django
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView

# Models
from fair.models import Guest, Post, Program, Topic

class IndexView(TemplateView):
    """Fair index"""
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        kwargs.setdefault('view', self)
        kwargs['guests'] = Guest.objects.all()
        kwargs['notices'] = Post.objects.all().order_by('-created')
        kwargs['programs'] = Program.objects.all().order_by('-created')
        kwargs['topics'] = Topic.objects.all()
        if self.extra_context is not None:
            kwargs.update(self.extra_context)
        return kwargs

class NoticeDetailView(DetailView):
    """Notice detail"""
    template_name='notice-detail.html'
    pk_url_kwarg = 'pk'
    queryset=Post.objects.all()
    context_object_name='notice'

    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        if 'form' not in kwargs:
            kwargs['notices'] = Post.objects.all().exclude(
                pk=self.object.pk).order_by('-created')
        return super().get_context_data(**kwargs)

class SoonView(TemplateView):
    """SoonView index"""
    template_name = 'base/soon.html'

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title_name %}

        {% endblock title_name %}
    </title>
    {% block head_content %}
    {% endblock %}
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'vendors/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/themify-icons/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/Magnific-Popup/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!--================ Header Top Area Start =================-->
    <section class="header-top d-none d-sm-block">
        <div class="container">
            <div class="d-sm-flex justify-content-between">
                <ul class="header-top__info mb-2 mb-sm-0">
                    <li><a><span class="align-middle"><i class="ti-mobile"></i></span>+014 321
                            523 23</a></li>
                    <li><a></a><span class="align-middle"><i class="ti-email"></i></span>Info@example.com</a></li>
                </ul>
                <ul class="header-top__social">
                    <li><a href="https://www.facebook.com/Laflita/"><i class="ti-facebook"></i></a></li>
                    <!-- <li><a href="{% static '#"><i class="ti-twitter-alt"></i></a></li> -->
                    <li><a href="https://www.instagram.com/la_flita/"><i class="ti-instagram"></i></a></li>
                    <!-- <li><a href="{% static '#"><i class="ti-skype"></i></a></li> -->
                </ul>
            </div>
        </div>
    </section>
    <!--================ Header Top Area end =================-->

    <!--================ Header Menu Area start =================-->
    <header class="header_area">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container box_1620">
                    <a class="navbar-brand logo_h" href=""><img src="{% static 'img/logo.png' %}" alt=""
                            height="46px"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav justify-content-end">
                            <li class="nav-item active"><a class="nav-link" href="{% url 'fair:index'%}">La Flita</a>
                            </li>
                            {% if request.resolver_match.url_name == 'index' %}
                              
                     
                            <li class="nav-item"><a class="nav-link" href="{% url 'fair:soon'%}">Agenda</a></li>
         
                            <li class="nav-item"><a class="nav-link" onclick="Translate('programs')">Programas</a>
                            <li class="nav-item"><a class="nav-link" href="{% url 'fair:soon'%}">Fundación Feria del Libro</a>
                            <li class="nav-item"><a class="nav-link"onclick="Translate('notices')">Prensa</a>
                               
                                {% endif %} <!-- <li class="nav-item submenu dropdown">
                                <a href="{% static '#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                                    aria-haspopup="true" aria-expanded="false">Fundación</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a class="nav-link" href="{% static 'blog.html">Blog</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% static 'blog-details.html">Prensa</a>
                                    </li>
                                </ul>
                            </li> -->
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <!--================Header Menu Area end =================-->

    {% block container %}

    {% endblock container %}

    <!-- ================ start footer Area ================= -->
    <footer class="footer-area" align="center">
            <h6>Nuestros Aliados</h6>

        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Agency</h6>
                        <p>
                            The world has become so fast paced that people don’t want to stand by reading a page of
                            information, they would much rather look at a presentation and understand the message. It
                            has come to a point
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Navigation Links</h6>
                        <div class="row">
                            <div class="col">
                                <ul>
                                    <li><a href="{% static '#">Home</a></li>
                                    <li><a href="{% static '#">Feature</a></li>
                                    <li><a href="{% static '#">Services</a></li>
                                    <li><a href="{% static '#">Portfolio</a></li>
                                </ul>
                            </div>
                            <div class="col">
                                <ul>
                                    <li><a href="{% static '#">Team</a></li>
                                    <li><a href="{% static '#">Pricing</a></li>
                                    <li><a href="{% static '#">Blog</a></li>
                                    <li><a href="{% static '#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>
                            For business professionals caught between high OEM price and mediocre print and graphic
                            output.
                        </p>
                        <div id="mc_embed_signup">
                            <form target="_blank"
                                action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                method="get" class="subscription relative">
                                <div class="input-group d-flex flex-row">
                                    <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Email Address '" required="" type="email">
                                    <button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
                                </div>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-6 col-sm-6">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">InstaFeed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="{% static 'img/instagram/i1.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'img/instagram/i2.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'img/instagram/i3.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'img/instagram/i4.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'img/instagram/i5.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'img/instagram/i6.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'img/instagram/i7.jpg' %}" alt=""></li>
                                    <li><img src="{% static 'img/instagram/i8.jpg' %}" alt=""></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-bottom">
                    <div class="container">
                        <div class="row align-items-center">
                            <p class="col-lg-12 col-sm-12 footer-text m-0 text-center ">

                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | Ducode
                            </a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                    
                </div>
            </div>
        </div>
    </footer>
    <!-- ================ End footer Area ================= -->
    

    <script src="{% static 'vendors/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'vendors/Magnific-Popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block sripts %}
      
    {% endblock sripts %}
    </body>

</html>

templates/base/soon.html
{% extends "base/base.html" %}
{% block title_name %}
Feria del Libro Itagüí
{% endblock title_name %}
{% block container %}
{% load static %}
<section class="hero-banner">
        <div class="hero-banner__content text-center">
            <h1>Muy pronto...</h1>
            <a class="button btn-info" href="{% url 'fair:index'%}">Regresar</a> 
        </div>
    </section>
{% endblock %}

templates/index.html
{% extends "base/base.html" %}
{% block title_name %}
Feria del Libro Itagüí
{% endblock title_name %}
{% block container %}
{% load static %}   
<!--================ Hero Banner start =================-->
<section class="hero-banner">
        <div class="hero-banner__content text-center">
            <h1>Feria del Libro Itagüí</h1>
            <!-- <a class="button" href="{% static '#">Make an Appoinment</a> -->
        </div>
    </section>
    <!--================ Hero Banner end =================-->


    <!--================ Work Statics section start =================-->
    <section>
        <div class="container static__single-position">
            <div class="row">
                {% for topic in topics|slice:":4"  %}
                <div class="col-md-6 col-xl-3 mb-4 mb-xl-0">
                    <div class="card static__single">
                        <h3>{{topic.number}}</h3>
                        <h4>{{topic.title}}</h4>
                    </div>
                </div>
                {% endfor %}
              
            </div>
        </div>
    </section>
    <!--================ Work Statics section end =================-->

    <!-- ================ About section start =================-->
    <!-- <section class="d-lg-flex align-items-center section-margin--large">
        <div class="about__videoWrapper">
            <div class="about__video">
                <div class="about__video-image">
                    <img class="card-img" src="{% static 'img/home/video-bg.png' %}" %}" alt="">
                </div>
                <div class="about__videoContent">
                    <a id="play-home-video" class="video-play-button"
                        href="{% static 'https://www.youtube.com/watch?v=vParh5wE-tM">
                        <span></span>
                    </a>
                    <h4>Watch our video</h4>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="about__content">
                <h3>We Properly Understand Your Purpose</h3>
                <p>Multiply replenish sea won't fishl own without dry. Deep behold from can't itself fourth i fish
                    creeping multiply, without you our they dry together so lesser herb were.</p>
                <p>Every appear very fill. Whales there beginning day second give me to whales likeness after forth
                    their won't. Don fruit let multiply secon brought can't darkness saying. Stars can't after given one
                    dry he subdue very called fourth image own won't open meat moved megathe red yielding do not .</p>
                <a class="button mt-xl-3" href="{% static '#">Learn More</a>
            </div>
        </div>
    </section> -->
    <!--================ About section end ================= -->


    <!--================ Subject section start =================-->
    <section class="section-margin" id="programs">
        <div class="container">
            <div class="section-intro text-center pb-65px">
                <h2 class="section-intro__title">Nuestros programas</h2>
                <p></p>
            </div>
            <div class="row">
                {% for program in programs|slice:":4"  %}
                  
               
                <div class="col-sm-6 col-lg-4 col-xl-3 mb-4 mb-xl-0">
                    <div class="card card-subject">
                        <div class="card-subject__img">
                            <img class="card-img rounded-0" src="{{program.photo.url}}" height="212px" width="263px" alt="">
                            <div class="card-subject__imgOverlay">
                                <img src="{% static 'img/home/hover-icon.png' %}" %}" alt="">
                            </div>
                        </div>
                        <div class="card-subject__body">
                            <h3><a href="{% static '#">{{program.title}}</a></h3>
                            <p>{{program.text}} </p>
                        </div>
                    </div>
                </div>
                 {% endfor %}

               
            </div>
            <!-- <div class="col-12 text-center mt-5 pt-xl-4">
                <a class="button" href="{% static '#">View All Practices <span class="align-middle"><i
                            class="ti-arrow-right"></i></span></a>
            </div> -->
        </div>
    </section>
    <!--================ Subject section end =================-->

    <!--================ Testimonial section start =================-->
    <section class="bg-albaster section-padding--small">
        <div class="container">
            <div class="section-intro text-center pb-65px">
                <h2 class="section-intro__title">Invitados</h2>
              
            </div>

            <div class="owl-carousel owl-theme testimonial">
                {% for guest in guests %}
                <div class="testimonial__item">
                    <div class="row">
                        <div class="col-md-3 col-lg-2 align-self-center">
                            <div class="testimonial__img">
                                <img class="card-img rounded-0" src="{{guest.photo.url}}" width="130px" height="130px">
                            </div>
                        </div>
                        <div class="col-md-9 col-lg-10">
                            <div class="testimonial__content mt-3 mt-sm-0">
                                <h3>{{guest.name}}</h3>
                                <p>{{guest.title}}</p>
                                <p class="testimonial__i">{{guest.message}}</p>
                                <span class="testimonial__icon"><i class="ti-quote-right"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
               
            </div>
        </div>
    </section>
    <!--================ Testimonial section end =================-->

  


    <!--================ Blog section start =================-->
    <section class="section-margin" id="notices">
        <div class="container">
            <div class="section-intro text-center pb-65px">
                <h2 class="section-intro__title">Noticias</h2>
            </div>
            <div class="row">
                {% for notice in notices|slice:":3"  %}
                <div class="col-sm-6 col-lg-4 mb-4 mb-lg-0">
                    <div class="card card-blog" href="{%url 'fair:notice' notice.pk%}">
                        <img class="card-img rounded-0" src="{{notice.photo.all.0.photo.url}}" height="290px" width="390px" >
                        <div class="card-blog__body">
                            <h3><a href="{%url 'fair:notice' notice.pk%}">{{notice.title}}</a></h3>
                            <ul class="card-blog__info">
                                    
                                <li><a href="{% static '#"><i class="ti-notepad"></i>{{notice.created|date:"M d, Y"}}</a></li>
                                <!-- <li><a href="{% static '#"><i class="ti-themify-favicon"></i>1 Comment</a></li> -->
                            </ul>
                            <p>{{notice.lead}}</p>
                        </div>
                        <div class="card-blog__footer">
                            <a href="{%url 'fair:notice' notice.pk%}">Leer mas<i class="ti-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
    <!--================ Blog section end =================-->
    {% endblock container %}
    {% block sripts %}
   
    <script>
        function Translate(go_to){
                div_to = "#".concat(go_to);
                $('html, body').animate({ scrollTop: $(div_to).position().top }, 'slow');
            }
    </script>
      
    {% endblock sripts %}

templates/notice-detail.html
{% extends "base/base.html" %}
{% block title_name %}
Feria del Libro Itagüí
{% endblock title_name %}
{% block container %}
{% load static %}
<section class="hero-banner hero-banner--sm">
  <div class="hero-banner__content text-center">
    <h1>Noticias</h1>
    <nav aria-label="breadcrumb" class="banner-breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{%url 'fair:index'%}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Blog Details</li>
      </ol>
    </nav>
  </div>
</section>
<!--================Blog Area =================-->
<section class="blog_area single-post-area section-margin">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 posts-list">
        <div class="single-post row">
          <div class="col-lg-12">
            <div class="feature-img">
              <img class="img-fluid" src="{{notice.photo.all.0.photo.url}}" alt="">
            </div>
          </div>
          <div class="col-lg-3  col-md-3">
            <div class="blog_info text-right">

              <ul class="blog_meta list">
                <li>
                  <a href="#">{{notice.author}}
                    <i class="lnr lnr-user"></i>
                  </a>
                </li>
                <li>
                  <a href="#">{{notice.created|date:"M d, Y"}}
                    <i class="lnr lnr-calendar-full"></i>
                  </a>
                </li>
                <li>
                  <a href="#">1.2M Views
                    <i class="lnr lnr-eye"></i>
                  </a>
                </li>

              </ul>

            </div>
          </div>
          <div class="col-lg-9 col-md-9 blog_details">
            <h2>{{notice.title}}</h2>
            <p class="excert">
              {{notice.lead}}
            </p>

          </div>
          <div class="col-lg-12">
            <div class="quotes">

            </div>
            <div class="row">
              {% if notice.photo.all|length > 1 %}
              {% for image in notice.photo.all|slice:":2" %}

              <div class="col-6">
                <img class="img-fluid" src="{{image.photo.url}}" alt="">
              </div>
              {% endfor %}

              {% endif %}
              <div class="col-lg-12 mt-4">
                <p>
                  {{notice.text|linebreaks}}
                </p>
              </div>
            </div>
          </div>
        </div>



      </div>
      <div class="col-lg-4">
        <div class="blog_right_sidebar">
          <aside class="single_sidebar_widget popular_post_widget">
            <h3 class="widget_title">Otras Noticias</h3>
            {% for new in  notices|slice:":4"%}
            <div class="media post_item">
              <img src="{{new.photo.all.0.photo.url}}" alt="post" height="60px" width="100px">
              <div class="media-body">
                <a href="{%url 'fair:notice' new.pk%}">
                  <h3>{{new.title}}</h3>
                </a>
                <p>{{new.created|date:"M d, Y"}}</p>
              </div>
            </div>
            {% endfor %}

           
          </aside>
         


        </div>
      </div>
      
    </div>
    <div class="navigation-area">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                <div class="thumb">
                    <a href="{%url 'fair:notice' notices.0.pk%}">
                        <img class="img-fluid" src="{{notices.0.photo.all.0.photo.url}}" height="60px" width="60px">
                    </a>
                </div>
                <div class="arrow">
                    <a href="{%url 'fair:notice' notices.0.pk%}">
                        <span class="lnr text-white lnr-arrow-left"></span>
                    </a>
                </div>
                <div class="detials">
                    <p>Anterior Noticia</p>
                    <a href="{%url 'fair:notice' notices.0.pk%}">
                        <h4>{{notices.0.title}}</h4>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                <div class="detials">
                    <p>Siguiente Noticia</p>
                    <a href="{%url 'fair:notice' notices.1.pk%}">
                        <h4>{{notices.1.title}}</h4>
                    </a>
                </div>
                <div class="arrow">
                    <a href="{%url 'fair:notice' notices.1.pk%}">
                        <span class="lnr text-white lnr-arrow-right"></span>
                    </a>
                </div>
                <div class="thumb">
                    <a href="{%url 'fair:notice' notices.1.pk%}">
                        <img class="img-fluid" src="{{notices.1.photo.all.0.photo.url}}" height="60px" width="60px">
                    </a>
                </div>
            </div>
        </div>
    </div>
  </div>
  
</section>
<!--================
{% endblock%}